const gulp = require('gulp')
const sass = require('gulp-sass')
const autoprefixer = require('gulp-autoprefixer')
const cleanCss = require('gulp-clean-css')
const sourceMap = require('gulp-sourcemaps')
const rename = require('gulp-rename')
module.exports = styles = (cd) => {
	return gulp.src('src/styles/*.scss')
		.pipe(sourceMap.init())
		.pipe(sass().on('error', sass.logError))
		.pipe(autoprefixer({overrideBrowserslist: ['last 2 version', '> 2%', 'firefox 15', 'safari 5', 'ie 6', 'ie 7', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4']}))
		.pipe(cleanCss())
		.pipe(rename('style.min.css'))
		.pipe(sourceMap.write('./maps'))
		.pipe(gulp.dest('build/css'))
}