const gulp = require('gulp')
const sass = require('gulp-sass')
const autoprefixer = require('gulp-autoprefixer')
const shorthand = require('gulp-shorthand')
const cleanCss = require('gulp-clean-css')
const sourceMap = require('gulp-sourcemaps')
const rename = require('gulp-rename')
// const styleLint = require('gulp-stylelint')
module.exports = styles = (cd) => {
	return gulp.src('src/styles/*.scss')
		.pipe(sourceMap.init())
		.pipe(sass())
		.pipe(autoprefixer())
		.pipe(shorthand())
		.pipe(cleanCss())
		.pipe(sourceMap.write())
		.pipe(rename('style.min.css'))
		.pipe(gulp.dest('build/css'))
}